### ISSUE TITLE
Initialize new node project with express

### ISSUE THREAD

**Issue by jchiatt** [DevLifts/devlifts-api#1]
The short-term goal is to implement a basic REST API and get it connected with our CLI app.

**Comment by alexluong** [comment]
Is there a reason why we're not starting with GraphQL?

**Comment by jchiatt** [comment]
@alexluong we’ve been moving pretty slow because of lots of other projects, so we decided to simplify just to get up and going and also try to make the project more accessible for Hacktoberfest. What do you think?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexluong** [comment]
Yeah I think that would work. Do you have anything yet? If you can push something up I can take it from there.

**Comment by jchiatt** [comment]
@alexluong I initialized a repo under the `jc/initialize_node_express` branch but haven't done anything yet (I haven't built a non-tutorial Node API before so I'm moving slow as I read through how to best do it).

Feel free to make some suggestions or even better, if you know how to at least get it going, make a couple of routes we can use as a launching point to create other routes!

@mtliendo may have more to say here too

**Comment by jchiatt** [comment]
Closing - completed in #2. However, opening new issues today.
